### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by at4260**

### CODE REVIEW

**Review by tone81 — COMMENTED** [review]
How do these enhancements provide value to our daily poses?

**Comment by at4260** [comment]
You have to think outside the box, @tone81. Poses aren't just about physical movement- it's about spiritual movement as well.

**Comment by tone81** [comment]
What if the person reviewing this is not spiritual in any sense of the word?

**Comment by at4260** [comment]
You don't have to have spirituality to be spiritual.  - Dalai Lama

**Comment by tone81** [comment]
You don't have to be spiritual - Tony Nguyen

**Review by tone81 — CHANGES_REQUESTED** [review]
If you can use better labeling for the **Red Power** or get rid of it, I'll merge this change.

**Review by tone81 — APPROVED** [review]

**Pull request merged**
